In [317]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 선형회귀 관련 sklean 라이브러리 불러오기

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# 선형회귀 관련 statsmodels 라이브러리 불러오기

import statsmodels.api as sm

In [318]:
# 간단한 맛보기 예제

np.array([[0,1],[1,2],[2,2.5]])

array([[0. , 1. ],
       [1. , 2. ],
       [2. , 2.5]])

In [319]:
np.array([0,1.2,1.6])

array([0. , 1.2, 1.6])

In [320]:
# 데이터

X = np.array([[0,1],[1,2],[2,2.5]]) # 2차원 데이터
y = np.array([0,1.2,1.6])

In [321]:
# 선형회귀 객체 생성

reg = linear_model.LinearRegression()

In [322]:
# 훈련 데이터 >> fit 모델 적합 
reg.fit(X,y)

LinearRegression()

In [323]:
# train data로 예측

pred_train = reg.predict(X)
pred_train

array([4.4408921e-16, 1.2000000e+00, 1.6000000e+00])

In [324]:
# coefficient (기울기, beta1, beta2)
reg.coef_

array([-0.4,  1.6])

In [325]:
# advertising 데이터 불러오기기

path = '/content/drive/MyDrive/새싹sw-인공지능 서비스 개발자/CLASSROOM/CODE PDF/머신러닝/Advertising.csv'
ad = pd.read_csv(path, index_col=0)

In [326]:
# train data의 feature의 결과변수 분리
ad.columns

Index(['Unnamed: 0.1', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [327]:
train = ad[:20]
test = ad[-20:]

In [328]:
train_X = train[['TV', 'Radio', 'Newspaper']]

train_y = train[['Sales']]

In [329]:
# test data의 feature의 결과변수 분리
train_X = test[['TV', 'Radio', 'Newspaper']]

train_y = test[['Sales']]

In [330]:
# 선형회귀 객체 생성
regr = linear_model.LinearRegression()


In [331]:
# train data 이용 >> fit (모델 적합)

regr.fit(train_X[['TV', 'Radio', 'Newspaper']],train_y)

LinearRegression()

In [332]:
# train data 활용, 예측

train_y_pred = regr.predict(train_X[['TV', 'Radio', 'Newspaper']])

In [333]:
# test data 활용, 예측

test_y_pred = regr.predict(train_X[['TV', 'Radio', 'Newspaper']])

In [334]:
print("coefficiants: ",regr.coef_)

coefficiants:  [[0.03593836 0.20758821 0.04053024]]


-----

In [335]:
# 다항회귀(polynominal features) 예제

In [336]:
from sklearn.preprocessing import PolynomialFeatures

In [337]:
X = np.arange(6).reshape(3,-1)

In [338]:
# [1,a,b,a^2,ab,b^2] feature 생성
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [339]:
# interaction(상호작용) feature만 생성

poly = PolynomialFeatures(interaction_only=True)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])

In [340]:
# auto data 활용, 다항회귀분석

path = '/content/drive/MyDrive/새싹sw-인공지능 서비스 개발자/CLASSROOM/CODE PDF/머신러닝/Auto.csv'
auto = pd.read_csv(path)

In [341]:
auto

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [342]:
# horsepower ? 값을 0 대체 

auto['horsepower'][:40]

0     130
1     165
2     150
3     150
4     140
5     198
6     220
7     215
8     225
9     190
10    170
11    160
12    150
13    225
14     95
15     95
16     97
17     85
18     88
19     46
20     87
21     90
22     95
23    113
24     90
25    215
26    200
27    210
28    193
29     88
30     90
31     95
32      ?
33    100
34    105
35    100
36     88
37    100
38    165
39    175
Name: horsepower, dtype: object

In [343]:
auto['horsepower']= auto['horsepower'].replace(to_replace='?',value=0)

In [344]:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
year              int64
origin            int64
name             object
dtype: object

In [345]:
# horsepower의 데이터타입 변경 (object >> numeric 숫자)

auto['horsepower'] = pd.to_numeric(auto['horsepower'])

In [346]:
auto['horsepower'].dtype

dtype('int64')

In [347]:
# auto data 다중선형회귀

# horsepower의 다양한 feature 생성

auto['horsepower_2'] = auto['horsepower']**2
auto['horsepower_3'] = auto['horsepower']**3
auto['horsepower_4'] = auto['horsepower']**4
auto['horsepower_5'] = auto['horsepower']**5
auto.head(5)


mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70   
1  15.0          8         350.0         165    3693          11.5    70   
2  18.0          8         318.0         150    3436          11.0    70   
3  16.0          8         304.0         150    3433          12.0    70   
4  17.0          8         302.0         140    3449          10.5    70   

   origin                       name  horsepower_2  horsepower_3  \
0       1  chevrolet chevelle malibu         16900       2197000   
1       1          buick skylark 320         27225       4492125   
2       1         plymouth satellite         22500       3375000   
3       1              amc rebel sst         22500       3375000   
4       1                ford torino         19600       2744000   

   horsepower_4  horsepower_5  
0     285610000   37129300000  
1     741200625  122298103125  
2     506250000   75937500000  
3     506250000   75937500000  
4     384160000   53782400000

In [348]:
# train/test data 분리 

train= auto[:-40]
test = auto[-40:]

print(train)
print(test)

      mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0    18.0          8         307.0         130    3504          12.0    70   
1    15.0          8         350.0         165    3693          11.5    70   
2    18.0          8         318.0         150    3436          11.0    70   
3    16.0          8         304.0         150    3433          12.0    70   
4    17.0          8         302.0         140    3449          10.5    70   
..    ...        ...           ...         ...     ...           ...   ...   
352  29.9          4          98.0          65    2380          20.7    81   
353  33.0          4         105.0          74    2190          14.2    81   
354  34.5          4         100.0           0    2320          15.8    81   
355  33.7          4         107.0          75    2210          14.4    81   
356  32.4          4         108.0          75    2350          16.8    81   

     origin                       name  horsepower_2  horsepowe

In [349]:
# 훈련용 데이터의 feature와 response 분리

auto.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name', 'horsepower_2',
       'horsepower_3', 'horsepower_4', 'horsepower_5'],
      dtype='object')

In [350]:
train_x =\
train[['horsepower','horsepower_2','horsepower_3', 'horsepower_4', 'horsepower_5']]

In [351]:
train_y = train[['mpg']]

In [352]:
test_x = test[['horsepower','horsepower_2','horsepower_3', 'horsepower_4', 'horsepower_5']]

In [353]:
test_y = test[['mpg']]

In [354]:
# 선형회귀 객체 생성

regr = linear_model.LinearRegression()

In [355]:
# 훈련용 데이터 이용 >> 모델 적합하게 한다. 

regr.fit(train_x[['horsepower','horsepower_2','horsepower_3']],train_y)

LinearRegression()

In [356]:
# 훈련용 데이터 이용, 예측

train_y_pred = regr.predict(train_x[['horsepower','horsepower_2','horsepower_3']])

In [357]:
# 테스트 데이터 이용, 예측 

test_y_pred = regr.predict(test_x[['horsepower','horsepower_2','horsepower_3']])

In [358]:
# coeffients

print('cofficents', regr.coef_)

cofficents [[ 8.89265767e-02 -2.94597040e-03  9.81651841e-06]]


In [359]:
# train data MSE

print('Train_data mse: %.3f'%mean_squared_error(train_y,train_y_pred))

Train_data mse: 19.819


In [360]:
# train data MSE

print('Train_data mse: %.3f'%mean_squared_error(test_y,test_y_pred))

Train_data mse: 38.104


In [361]:
# train data r2_score

print('r2_score: %.3f'%r2_score(train_y,train_y_pred))

r2_score: 0.660


In [362]:
# test data r2_score

print('r2_score: %.3f'%r2_score(test_y,test_y_pred))

r2_score: -0.179
