In [3]:
# 재표본 추출 방법 (resampling method)

import numpy as np
import pandas as pd

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Resampling 관련 라이브러리

from sklearn.model_selection import KFold # k- fold 교차검증
from sklearn.utils import resample # bootstrap

# 임의로 데이터를 섞기 위한 라이브러리 (random shuffling)
# 편향 (bias) 방지하기 위해서

from sklearn.utils import shuffle

# 붓꽃(iris) 데이터 로딩 
from sklearn.datasets import load_iris

In [10]:
# K-fold 맛보기 
X = ['a','b','c','d']
kf = KFold(n_splits=2) # 2개로 나누기 

for train, test in kf.split(X):
  print("%s %s"%(train, test))
  print(X[train[0]], X[train[1]],X[test[0]], X[test[1]])

[2 3] [0 1]
c d a b
[0 1] [2 3]
a b c d


In [11]:
# 붓꽃 (iris) 데이터 예제_ k-fold cross validation

In [12]:
X_iris, y_iris = load_iris(return_X_y = True) 

In [13]:
X_iris[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [14]:
y_iris # 라벨링링

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
# 데이터를 임의로 섞기 

X_iris, y_iris= shuffle(X_iris,y_iris)

In [17]:
X_iris

array([[5. , 3.4, 1.5, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [6.5, 3. , 5.8, 2.2],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.3, 5.7, 2.1],
       [6.4, 2.9, 4.3, 1.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 4.2, 1.4, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [5.4, 3. , 4.5, 1.5],
       [4.8, 3. , 1.4, 0.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.8, 2.7, 4.1, 1. ],
       [5. , 3.5, 1.6, 0.6],
       [6.9, 3.1, 5.1, 2.3],
       [4.9, 2.4, 3.3, 1. ],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 3. , 4.2, 1.2],
       [6. , 3.4, 4.5, 1.6],
       [6.1, 3. , 4.6, 1.4],
       [6.3, 3.3, 4.7, 1.6],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.5, 4.9, 1.5],
       [5.1, 3.5, 1.4, 0.3],
       [6.2, 2.8, 4.8, 1.8],
       [5.9, 3. , 5.1, 1.8],
       [6.2, 2.2, 4.5, 1.5],
       [7.7, 2.6, 6.9, 2.3],
       [5.1, 3.8, 1.6, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.4, 2.7, 5.3, 1.9],
       [4.8, 3

In [18]:
y_iris

array([0, 0, 2, 2, 0, 2, 1, 1, 0, 2, 1, 0, 1, 1, 0, 2, 1, 2, 1, 1, 1, 1,
       2, 1, 0, 2, 2, 1, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 1, 1, 0, 0,
       0, 2, 1, 0, 2, 2, 0, 1, 1, 0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1,
       1, 2, 0, 0, 2, 1, 1, 0, 2, 1, 1, 2, 1, 2, 2, 2, 0, 0, 2, 0, 1, 2,
       2, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 1, 2, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 2, 1, 2, 0, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1,
       2, 2, 0, 0, 2, 0, 1, 1, 0, 2, 2, 0, 0, 0, 2, 1, 0, 2])

In [23]:
# 5 fold cross validation

kf = KFold(n_splits=5)

idx = 1

for train, val in kf.split(X_iris):
  print("Fold: #", idx)

  # k-fold 결과 확인 
  print('%s %s'%(train, val))
  print(y_iris[train])
  print(y_iris[val])

  print('----------')
  idx+=1
  

Fold: # 1
[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[0 0 0 2 0 0 0 2 2 0 1 1 0 0 0 2 1 0 2 2 0 1 1 0 1 2 1 2 2 2 2 2 2 1 2 1 1
 2 0 0 2 1 1 0 2 1 1 2 1 2 2 2 0 0 2 0 1 2 2 0 1 0 1 0 0 0 1 0 0 0 2 0 0 2
 1 2 1 0 1 0 1 1 0 1 0 1 1 2 1 2 0 1 1 2 1 2 1 2 1 2 1 1 2 2 0 0 2 0 1 1 0
 2 2 0 0 0 2 1 0 2]
[0 0 2 2 0 2 1 1 0 2 1 0 1 1 0 2 1 2 1 1 1 1 2 1 0 2 2 1 2 0]
----------
Fold: # 2
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19

In [27]:
# 5 fold cross validation

kf = KFold(n_splits=5)

idx = 1

for train, val in kf.split(X_iris):
  print("Fold: #", idx)

  # k-fold 결과 확인 
  # print('%s %s'%(train, val))
  # print(y_iris[train])
  # print(y_iris[val])

  # LDA (분류 알고리즘)
  # 훈련 (train data로만 훈련)
  clf = LinearDiscriminantAnalysis().fit(X_iris[train],y_iris[train])

  # 클래스 예측
  print('true label: ',y_iris[val])
  print('predicted label: ', clf.predict(X_iris[val]))

  # 정확도(accuracy)
  print('정확도(accuracy): ',clf.score(X_iris[val], y_iris[val]))


  print('----------')
  idx+=1

Fold: # 1
true label:  [0 0 2 2 0 2 1 1 0 2 1 0 1 1 0 2 1 2 1 1 1 1 2 1 0 2 2 1 2 0]
predicted label:  [0 0 2 2 0 2 1 1 0 2 1 0 1 1 0 2 1 2 1 1 1 1 2 1 0 2 2 1 2 0]
정확도(accuracy):  1.0
----------
Fold: # 2
true label:  [0 0 0 2 0 0 0 2 2 0 1 1 0 0 0 2 1 0 2 2 0 1 1 0 1 2 1 2 2 2]
predicted label:  [0 0 0 2 0 0 0 2 2 0 1 1 0 0 0 2 1 0 2 2 0 1 1 0 1 2 1 2 2 2]
정확도(accuracy):  1.0
----------
Fold: # 3
true label:  [2 2 2 1 2 1 1 2 0 0 2 1 1 0 2 1 1 2 1 2 2 2 0 0 2 0 1 2 2 0]
predicted label:  [2 2 2 1 2 1 2 2 0 0 2 1 1 0 2 1 1 2 1 2 2 2 0 0 2 0 1 2 2 0]
정확도(accuracy):  0.9666666666666667
----------
Fold: # 4
true label:  [1 0 1 0 0 0 1 0 0 0 2 0 0 2 1 2 1 0 1 0 1 1 0 1 0 1 1 2 1 2]
predicted label:  [1 0 1 0 0 0 1 0 0 0 2 0 0 2 1 2 1 0 1 0 1 1 0 2 0 1 1 2 1 2]
정확도(accuracy):  0.9666666666666667
----------
Fold: # 5
true label:  [0 1 1 2 1 2 1 2 1 2 1 1 2 2 0 0 2 0 1 1 0 2 2 0 0 0 2 1 0 2]
predicted label:  [0 1 1 1 1 2 1 2 1 2 1 1 2 2 0 0 2 0 1 1 0 2 2 0 0 0 2 1 0 2]
정확도(accuracy):  0.966

In [29]:
# bootstrap 맛보기

X = np.array([[1.,0.],[2.,1.],[0.,0.]])
y = np.array([0,1,2])

X,y = resample(X,y)

In [30]:
X,y

(array([[2., 1.],
        [1., 0.],
        [1., 0.]]), array([1, 0, 0]))

In [32]:
# lris 데이터 활용, bootstrap 예제 

X_iris, y_iris = load_iris(return_X_y= True)

X,y = resample(X_iris, y_iris)

In [33]:
print(X)
print(y)

[[6.8 3.  5.5 2.1]
 [4.6 3.1 1.5 0.2]
 [6.4 3.2 5.3 2.3]
 [5.7 3.8 1.7 0.3]
 [6.6 3.  4.4 1.4]
 [5.  3.3 1.4 0.2]
 [6.4 2.7 5.3 1.9]
 [4.9 2.4 3.3 1. ]
 [6.1 2.8 4.  1.3]
 [7.2 3.  5.8 1.6]
 [6.1 2.8 4.  1.3]
 [6.3 2.8 5.1 1.5]
 [6.4 3.2 4.5 1.5]
 [5.1 3.3 1.7 0.5]
 [5.6 3.  4.5 1.5]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [4.8 3.  1.4 0.1]
 [6.  3.4 4.5 1.6]
 [6.5 3.2 5.1 2. ]
 [6.1 2.6 5.6 1.4]
 [4.6 3.6 1.  0.2]
 [7.2 3.6 6.1 2.5]
 [6.3 2.5 4.9 1.5]
 [6.9 3.1 5.1 2.3]
 [7.  3.2 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [5.1 3.3 1.7 0.5]
 [6.1 3.  4.6 1.4]
 [5.4 3.9 1.7 0.4]
 [5.1 3.8 1.9 0.4]
 [6.3 2.5 4.9 1.5]
 [6.3 2.3 4.4 1.3]
 [5.4 3.7 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [4.9 2.5 4.5 1.7]
 [6.  3.4 4.5 1.6]
 [5.7 3.  4.2 1.2]
 [5.  2.3 3.3 1. ]
 [5.  3.  1.6 0.2]
 [6.1 3.  4.9 1.8]
 [7.7 2.6 6.9 2.3]
 [6.9 3.2 5.7 2.3]
 [7.3 2.9 6.3 1.8]
 [6.8 2.8 4.8 1.4]
 [4.4 3.  1.3 0.2]
 [5.1 3.8 1.9 0.4]
 [5.7 2.8 4.1 1.3]
 [5.1 3.8 1.6 0.2]
 [6.3 2.8 5.1 1.5]
 [5.5 2.4 3.7 1. ]
 [5.7 2.9 4.

In [34]:
# unique한 값 및 개수 출력

unique, counts = np.unique(y, return_counts=True)

In [35]:
unique

array([0, 1, 2])

In [36]:
counts

array([52, 54, 44])